## edit this file and save it as config.yml

# google reader settings
user: "username@gmail.com"
password: "your_password"

# settings for your iPhone / iPod Touch
iphone_hostname: "iPod.local"
iphone_user: "root"

# not necessary to provide if you have set
# up authorized ssh-keys for your iPhone:
iphone_password: "dottie"
