#!/bin/bash

config="/tmp/GRiS"
if [ -f "$config" ]; then
	echo "copying old config..."
	cp "$config/*" /var/mobile/GRiS/ || exit 1
fi
chown -R mobile.mobile /var/mobile/GRiS

if [ "$1" == 'configure' ]; then
	echo "$2" > /var/mobile/GRiS/VERSION
fi